server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: sc-provider

spring:
  application:
    name: sc-provider
  cloud:
    config:
      discovery:
        enabled: true
        service-id: sc-config-server
      fail-fast: true
      username: admin
      password: admin
      profile: csdn
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1.0

